//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceAndDirectionLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistanceAndDirectionLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate.
        /// </summary>
        public static string AEInvalidCoordinate {
            get {
                return ResourceManager.GetString("AEInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string AEInvalidInput {
            get {
                return ResourceManager.GetString("AEInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be positive.
        /// </summary>
        public static string AEMustBePositive {
            get {
                return ResourceManager.GetString("AEMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of radials must be between {0} and {1}.
        /// </summary>
        public static string AENumOfRadials {
            get {
                return ResourceManager.GetString("AENumOfRadials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rings must be between {0} and {1}.
        /// </summary>
        public static string AENumOfRings {
            get {
                return ResourceManager.GetString("AENumOfRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance and Bearing.
        /// </summary>
        public static string EnumBearingAndDistance {
            get {
                return ResourceManager.GetString("EnumBearingAndDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string EnumCTDD {
            get {
                return ResourceManager.GetString("EnumCTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string EnumCTDDM {
            get {
                return ResourceManager.GetString("EnumCTDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string EnumCTDMS {
            get {
                return ResourceManager.GetString("EnumCTDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string EnumCTGARS {
            get {
                return ResourceManager.GetString("EnumCTGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string EnumCTMGRS {
            get {
                return ResourceManager.GetString("EnumCTMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Map Unit.
        /// </summary>
        public static string EnumCTNone {
            get {
                return ResourceManager.GetString("EnumCTNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string EnumCTUSNG {
            get {
                return ResourceManager.GetString("EnumCTUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string EnumCTUTM {
            get {
                return ResourceManager.GetString("EnumCTUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string EnumDegrees {
            get {
                return ResourceManager.GetString("EnumDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string EnumDiameter {
            get {
                return ResourceManager.GetString("EnumDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string EnumFeet {
            get {
                return ResourceManager.GetString("EnumFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet / Hour.
        /// </summary>
        public static string EnumFeetHour {
            get {
                return ResourceManager.GetString("EnumFeetHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet / Second.
        /// </summary>
        public static string EnumFeetSec {
            get {
                return ResourceManager.GetString("EnumFeetSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string EnumFull {
            get {
                return ResourceManager.GetString("EnumFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic.
        /// </summary>
        public static string EnumGeodesic {
            get {
                return ResourceManager.GetString("EnumGeodesic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Elliptic.
        /// </summary>
        public static string EnumGreatElliptic {
            get {
                return ResourceManager.GetString("EnumGreatElliptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string EnumKilometers {
            get {
                return ResourceManager.GetString("EnumKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers / Hour.
        /// </summary>
        public static string EnumKilometersHour {
            get {
                return ResourceManager.GetString("EnumKilometersHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers / Second.
        /// </summary>
        public static string EnumKilometersSec {
            get {
                return ResourceManager.GetString("EnumKilometersSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loxodrome.
        /// </summary>
        public static string EnumLoxodrome {
            get {
                return ResourceManager.GetString("EnumLoxodrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string EnumMeters {
            get {
                return ResourceManager.GetString("EnumMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters / Hour.
        /// </summary>
        public static string EnumMetersHour {
            get {
                return ResourceManager.GetString("EnumMetersHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters / Second.
        /// </summary>
        public static string EnumMetersSec {
            get {
                return ResourceManager.GetString("EnumMetersSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string EnumMiles {
            get {
                return ResourceManager.GetString("EnumMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles / Hour.
        /// </summary>
        public static string EnumMilesHour {
            get {
                return ResourceManager.GetString("EnumMilesHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles / Second.
        /// </summary>
        public static string EnumMilesSec {
            get {
                return ResourceManager.GetString("EnumMilesSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mils.
        /// </summary>
        public static string EnumMils {
            get {
                return ResourceManager.GetString("EnumMils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        public static string EnumNauticalMile {
            get {
                return ResourceManager.GetString("EnumNauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles / Hour.
        /// </summary>
        public static string EnumNauticalMilesHour {
            get {
                return ResourceManager.GetString("EnumNauticalMilesHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles / Second.
        /// </summary>
        public static string EnumNauticalMilesSec {
            get {
                return ResourceManager.GetString("EnumNauticalMilesSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string EnumPoints {
            get {
                return ResourceManager.GetString("EnumPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string EnumRadius {
            get {
                return ResourceManager.GetString("EnumRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi.
        /// </summary>
        public static string EnumSemi {
            get {
                return ResourceManager.GetString("EnumSemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        public static string EnumYards {
            get {
                return ResourceManager.GetString("EnumYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string LabelAngle {
            get {
                return ResourceManager.GetString("LabelAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string LabelAxisGroup {
            get {
                return ResourceManager.GetString("LabelAxisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string LabelAxisUnits {
            get {
                return ResourceManager.GetString("LabelAxisUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Point.
        /// </summary>
        public static string LabelCenterPoint {
            get {
                return ResourceManager.GetString("LabelCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Graphics.
        /// </summary>
        public static string LabelClearGraphics {
            get {
                return ResourceManager.GetString("LabelClearGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string LabelCreateCircleFrom {
            get {
                return ResourceManager.GetString("LabelCreateCircleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ellipse with.
        /// </summary>
        public static string LabelCreateEllipseWith {
            get {
                return ResourceManager.GetString("LabelCreateEllipseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Feature.
        /// </summary>
        public static string LabelCreateFeature {
            get {
                return ResourceManager.GetString("LabelCreateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction / Azimuth.
        /// </summary>
        public static string LabelDirectionAzimuth {
            get {
                return ResourceManager.GetString("LabelDirectionAzimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Coordinate.
        /// </summary>
        public static string LabelDisplayCoordinate {
            get {
                return ResourceManager.GetString("LabelDisplayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Calculator.
        /// </summary>
        public static string LabelDistanceCalculator {
            get {
                return ResourceManager.GetString("LabelDistanceCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance / Length.
        /// </summary>
        public static string LabelDistanceLength {
            get {
                return ResourceManager.GetString("LabelDistanceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse Type.
        /// </summary>
        public static string LabelEllipseType {
            get {
                return ResourceManager.GetString("LabelEllipseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Point.
        /// </summary>
        public static string LabelEndingPoint {
            get {
                return ResourceManager.GetString("LabelEndingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive.
        /// </summary>
        public static string LabelInteractive {
            get {
                return ResourceManager.GetString("LabelInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Between Rings.
        /// </summary>
        public static string LabelInterval {
            get {
                return ResourceManager.GetString("LabelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string LabelMajorAxis {
            get {
                return ResourceManager.GetString("LabelMajorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Point.
        /// </summary>
        public static string LabelMapPoint {
            get {
                return ResourceManager.GetString("LabelMapPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string LabelMinorAxis {
            get {
                return ResourceManager.GetString("LabelMinorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Radials.
        /// </summary>
        public static string LabelNumberOfRadials {
            get {
                return ResourceManager.GetString("LabelNumberOfRadials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rings.
        /// </summary>
        public static string LabelNumberOfRings {
            get {
                return ResourceManager.GetString("LabelNumberOfRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string LabelOrientationAngle {
            get {
                return ResourceManager.GetString("LabelOrientationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string LabelOrientationGroup {
            get {
                return ResourceManager.GetString("LabelOrientationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string LabelOrientationUnit {
            get {
                return ResourceManager.GetString("LabelOrientationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string LabelRadius {
            get {
                return ResourceManager.GetString("LabelRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius / Diameter.
        /// </summary>
        public static string LabelRadiusDiameter {
            get {
                return ResourceManager.GetString("LabelRadiusDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Point.
        /// </summary>
        public static string LabelRangeRingsCenterPoint {
            get {
                return ResourceManager.GetString("LabelRangeRingsCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between Rings.
        /// </summary>
        public static string LabelRangeRingsDistanceBetween {
            get {
                return ResourceManager.GetString("LabelRangeRingsDistanceBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Radials.
        /// </summary>
        public static string LabelRangeRingsNumberofRadials {
            get {
                return ResourceManager.GetString("LabelRangeRingsNumberofRadials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string LabelRate {
            get {
                return ResourceManager.GetString("LabelRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string LabelSaveAs {
            get {
                return ResourceManager.GetString("LabelSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Point.
        /// </summary>
        public static string LabelStartingPoint {
            get {
                return ResourceManager.GetString("LabelStartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string LabelTabCircle {
            get {
                return ResourceManager.GetString("LabelTabCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string LabelTabEllipse {
            get {
                return ResourceManager.GetString("LabelTabEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LabelTabLines {
            get {
                return ResourceManager.GetString("LabelTabLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        public static string LabelTabRange {
            get {
                return ResourceManager.GetString("LabelTabRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TitleEditProperties {
            get {
                return ResourceManager.GetString("TitleEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TooltipEditProperties {
            get {
                return ResourceManager.GetString("TooltipEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Point Tool.
        /// </summary>
        public static string TooltipMapPointTool {
            get {
                return ResourceManager.GetString("TooltipMapPointTool", resourceCulture);
            }
        }
    }
}
